/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lesktimo.oskillaattori.gui;

/**
 *
 * @author lesktimo
 */
public class Syotepaneeli extends javax.swing.JPanel {

    /**
     * Creates new form Syotepaneeli
     */
    public Syotepaneeli() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        syoteKentta = new javax.swing.JTextField();
        soittoNappi = new javax.swing.JToggleButton();
        tempoKentta = new javax.swing.JTextField();
        tempoTeksti = new javax.swing.JLabel();
        soitonSeuranta = new javax.swing.JProgressBar();
        tyhjennaNappi = new javax.swing.JButton();

        syoteKentta.setText("Kirjoita tähän nuotteja ja niiden pituuksia pilkuilla erotettuina, esim. 'C4 1/4, tauko 1/8,  D#4 1/8'.");
        syoteKentta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                syoteKenttaActionPerformed(evt);
            }
        });

        soittoNappi.setText("Soita");
        soittoNappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soittoNappiActionPerformed(evt);
            }
        });

        tempoKentta.setText("120.00");
        tempoKentta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempoKenttaActionPerformed(evt);
            }
        });

        tempoTeksti.setText("Tempo:");

        tyhjennaNappi.setText("Tyhjennä");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(syoteKentta, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tempoTeksti)
                .addGap(0, 0, 0)
                .addComponent(tempoKentta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soitonSeuranta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soittoNappi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tyhjennaNappi, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(syoteKentta, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tempoKentta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tempoTeksti)
                        .addComponent(soitonSeuranta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(soittoNappi)
                        .addComponent(tyhjennaNappi)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void soittoNappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soittoNappiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soittoNappiActionPerformed

    private void tempoKenttaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempoKenttaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempoKenttaActionPerformed

    private void syoteKenttaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_syoteKenttaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_syoteKenttaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar soitonSeuranta;
    private javax.swing.JToggleButton soittoNappi;
    private javax.swing.JTextField syoteKentta;
    private javax.swing.JTextField tempoKentta;
    private javax.swing.JLabel tempoTeksti;
    private javax.swing.JButton tyhjennaNappi;
    // End of variables declaration//GEN-END:variables
}
